name: Playwright Tests
on:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Wait for Vercel Preview
        id: wait_for_preview
        run: |
          # Maximum wait time in seconds (10 minutes)
          max_wait=600
          wait_interval=15
          elapsed=0

          while [ $elapsed -lt $max_wait ]; do
            PR_NUMBER=${{ github.event.pull_request.number }}
            DEPLOYMENTS=$(curl -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
                        "https://api.vercel.com/v5/now/deployments")
            
            PREVIEW_URL=$(echo $DEPLOYMENTS | jq -r --arg prNum "$PR_NUMBER" \
                        '.deployments[] | select(.meta.githubPrId == $prNum and .state == "READY") | .url' | head -n 1)
            
            if [ ! -z "$PREVIEW_URL" ]; then
              if [[ $PREVIEW_URL != http* ]]; then
                PREVIEW_URL="https://$PREVIEW_URL"
              fi
              
              # Verify the deployment is actually accessible
              HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$PREVIEW_URL")
              
              if [ "$HTTP_STATUS" = "200" ]; then
                echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_OUTPUT
                echo "Preview URL found and verified: $PREVIEW_URL"
                
                # Additional wait to ensure application is fully ready
                sleep 30
                exit 0
              else
                echo "Preview URL found but returned status $HTTP_STATUS. Waiting for it to be ready..."
              fi
            fi
            
            echo "Waiting for Vercel preview deployment... (${elapsed}s elapsed)"
            sleep $wait_interval
            elapsed=$((elapsed + wait_interval))
          done

          echo "Timeout waiting for Vercel preview deployment"
          exit 1
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Run Playwright tests
        run: |
          # Log the URL we're testing against
          echo "Testing against URL: $PLAYWRIGHT_TEST_BASE_URL"
          pnpm exec playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.wait_for_preview.outputs.PREVIEW_URL }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
